### PR TITLE
Couple of changes to fix logs

### LINKED ISSUE #58: opcap fails on check - logs folder doesn't exist
@yashoza19 do we really need to store logs to files at this point? If so the file path is hard coded to a logs folder that is not created or existent on any system. I would advocate to avoid storing log files. Maybe let's use the root where opcap binary is seating no matter where it is. Users should have privileges to run and create files on that particular folder. Here is what happens:
```
panic: couldn't open sink "logs/stdout.json": open logs/stdout.json: no such file or directory

goroutine 1 [running]:
opcap/internal/logger.init.0()
        /Users/alex/go/src/github.com/acmenezes/opcap/internal/logger/zap.go:32 +0x1df
exit status 2
```

### PR DESCRIPTION
**Pull request by yashoza19**
- Changing logs to be printed with (level)w instead of (level)f - Closes #57 
- Changing the path to store logs - Closes #58 

Signed-off-by: Yash Oza <yoyashoza@gmail.com>

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -25,4 +25,6 @@ openshift/*
 openshift
 /build
 /.vscode
-/logs
\ No newline at end of file
+/logs
+
+/std_*.json
```
Comment (mrhillsman) [inline .gitignore:30]: Remove _

File: internal/capability/operator_install.go [hunk 2]
```diff
@@ -47,7 +47,7 @@ func OperatorInstallAllFromCatalog(catalogSource string, catalogSourceNamespace
 
 func OperatorInstall(s operator.SubscriptionData, c operator.Client) error {
 
-	logger.Debugf("Installing %s from channel %s install mode %s ", s.Package, s.Channel, s.InstallModeType)
+	logger.Debugw("Installing Pacakge", s.Package, "Channel", s.Channel, "InstallMode", s.InstallModeType)
```
Comment (mrhillsman) [inline internal/capability/operator_install.go:50]: Pacakge should be Package

**Review by mrhillsman — CHANGES_REQUESTED** [review]
I left a few comments but after going through it is better to leave overall comment. So the format for using (Level)w is:

```go
(msg string, keysAndValues ...interface{})
```

Some of the uses of Errorw for example are not following this format. If you only want to have a message provided concatenate err to string or use (Level)f as before; i.e. you do not want to add any additional keys to the log object you just want to provide a value to the message key.

File: internal/capability/operator_install.go [hunk 3]
```diff
@@ -37,7 +37,7 @@ func OperatorInstallAllFromCatalog(catalogSource string, catalogSourceNamespace
 		// of it's operator dedicated goroutine
 		err := OperatorInstall(subscription, c)
 		if err != nil {
-			logger.Errorf("Package %s, channel %s, install mode %s - FAILED to complete test", subscription.Package, subscription.Channel, subscription.InstallModeType)
+			logger.Errorw("Package", subscription.Package, "channel", subscription.Channel, "install mode", subscription.InstallModeType)
```
Comment (mrhillsman) [inline internal/capability/operator_install.go:40]: Errorw signature is (msg string, keysAndValues ...interface{}). A message is needed and the key/value pairs should be lowercase with no spaces; package vs Package and installmode vs install mode

File: internal/capability/operator_install.go [hunk 4]
```diff
@@ -99,19 +99,19 @@ func OperatorInstall(s operator.SubscriptionData, c operator.Client) error {
 	// create subscription per operator package/channel
 	sub, err := c.CreateSubscription(context.Background(), s, namespace)
 	if err != nil {
-		logger.Debugf("Error creating subscriptions: %s", err)
+		logger.Debugw("Error creating subscriptions: %w", err)
```
Comment (mrhillsman) [inline internal/capability/operator_install.go:102]: Should be Debugf vs Debugw?

File: internal/operator/client.go [hunk 5]
```diff
@@ -75,7 +75,7 @@ func NewPackageServerClient() (*pkgsclientv1.Clientset, error) {
 
 	cfg, err := clientcmd.BuildConfigFromFlags("", os.Getenv("KUBECONFIG"))
 	if err != nil {
-		logger.Errorf("Unable to build config from flags: %v", err)
+		logger.Errorf("Unable to build config from flags", err)
```
Comment (mrhillsman) [inline internal/operator/client.go:78]: String format error

File: internal/operator/install_plan.go [hunk 6]
```diff
@@ -35,17 +35,17 @@ func (c operatorClient) InstallPlanApprove(namespace string) error {
...
-		logger.Errorf("no installPlan found in namespace %s: %s", namespace, err)
+		logger.Errorf("no installPlan found in namespace %s: %w", namespace, err)
 		return err
 	}
 
 	if installPlan.Spec.Approval == operatorv1alpha1.ApprovalManual {
 
 		installPlan.Spec.Approved = true
-		logger.Debugf("InstallPlan %s approved by opcap on namespace %s", installPlan.ObjectMeta.Name, namespace)
+		logger.Debugw("InstallPlan Approved", installPlan.ObjectMeta.Name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/install_plan.go:45]: Debugw format (msg string, keysAndValues ...interface{}); installPlan.ObjectMeta.Name needs a key, "Namespace" should be "namespace"

File: internal/operator/install_plan.go [hunk 7]
```diff
@@ -35,17 +35,17 @@ func (c operatorClient) InstallPlanApprove(namespace string) error {
...
 		err := c.Client.Update(context.Background(), &installPlan)
 		if err != nil {
-			logger.Errorf("Error while updating InstallPlan Spec :%s", err)
+			logger.Errorw("Error", err)
```
Comment (mrhillsman) [inline internal/operator/install_plan.go:48]: Errorf?

File: internal/operator/namespace.go [hunk 8]
```diff
@@ -32,21 +32,21 @@ func CreateNamespace(ctx context.Context, name string) (*corev1.Namespace, error
 	}
 	_, err := operatorClient.CoreV1().Namespaces().Create(ctx, &nsSpec, metav1.CreateOptions{})
 	if err != nil {
-		logger.Errorf("error while creating Namespace %s: %s", name, err)
+		logger.Errorf("error while creating Namespace %s: %w", name, err)
 		return nil, err
 	}
-	logger.Debugf("Namespace Created: %s", name)
+	logger.Debugw("Namespace Created", name)
```
Comment (mrhillsman) [inline internal/operator/namespace.go:38]: Debugf? If using Debugw need to fix format; (msg string, keysAndValues ...interface{})

File: internal/operator/namespace.go [hunk 9]
```diff
@@ -32,21 +32,21 @@ func CreateNamespace(ctx context.Context, name string) (*corev1.Namespace, error
...
 	return &nsSpec, nil
 }
 
 func DeleteNamespace(ctx context.Context, name string) error {
 	operatorClient := GetK8sClient()
-	logger.Debugf("Deleting namespace: %s", name)
+	logger.Debugw("Delete namespace", name)
```
Comment (mrhillsman) [inline internal/operator/namespace.go:44]: Debugf? If using Debugw need to fix format; (msg string, keysAndValues ...interface{})

File: internal/operator/namespace.go [hunk 10]
```diff
@@ -32,21 +32,21 @@ func CreateNamespace(ctx context.Context, name string) (*corev1.Namespace, error
...
 	err := operatorClient.CoreV1().Namespaces().Delete(ctx, name, metav1.DeleteOptions{})
 	if err != nil {
-		logger.Errorf("error while deleting Namespace %s: %s", name, err)
+		logger.Errorf("error while deleting Namespace %s: %w", name, err)
 		return err
 	}
-	logger.Debugf("Namespace Deleted: %s", name)
+	logger.Debugw("Namespace Deleted", name)
```
Comment (mrhillsman) [inline internal/operator/namespace.go:50]: Debugf? If using Debugw need to fix format; (msg string, keysAndValues ...interface{})

File: internal/operator/operator_group.go [hunk 11]
```diff
@@ -14,7 +14,7 @@ type OperatorGroupData struct {
 }
 
 func (o *operatorClient) CreateOperatorGroup(ctx context.Context, data OperatorGroupData, namespace string) (*operatorv1.OperatorGroup, error) {
-	logger.Debugf("Creating OperatorGroup %s in namespace %s", data.Name, namespace)
+	logger.Debugw("Creating OperatorGroup", data.Name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:17]: Debugw need to fix format; (msg string, keysAndValues ...interface{})
logger.Debugw("Creating OperatorGroup", "operatorgroup", data.Name, "namespace", namespace)?

File: internal/operator/operator_group.go [hunk 12]
```diff
@@ -26,16 +26,16 @@ func (o *operatorClient) CreateOperatorGroup(ctx context.Context, data OperatorG
 	}
 	err := o.Client.Create(ctx, operatorGroup)
 	if err != nil {
-		logger.Errorf("error while creating OperatorGroup %s: %s", data.Name, err)
+		logger.Errorf("error while creating OperatorGroup %s: %w", data.Name, err)
 		return nil, err
 	}
 
-	logger.Debugf("OperatorGroup %s is created successfully in namespace %s", data.Name, namespace)
+	logger.Debugw("OperatorGroup created", data.Name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:33]: Same as previous comment.

File: internal/operator/operator_group.go [hunk 13]
```diff
@@ -26,16 +26,16 @@ func (o *operatorClient) CreateOperatorGroup(ctx context.Context, data OperatorG
...
 	return operatorGroup, nil
 }
 
 func (o *operatorClient) DeleteOperatorGroup(ctx context.Context, name string, namespace string) error {
-	logger.Debugf("Deleting OperatorGroup %s in namespace %s", name, namespace)
+	logger.Debugw("Deleting OperatorGroup", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:38]: Same as previous comment.

File: internal/operator/secret.go [hunk 14]
```diff
@@ -24,11 +24,11 @@ func (o operatorClient) CreateSecret(ctx context.Context, name string, content m
 	}
 	err := o.Client.Create(ctx, &secret, &runtimeClient.CreateOptions{})
 	if err != nil {
-		logger.Errorf("error while creating secret: %s in namespace: %s", name, namespace, err)
+		logger.Errorf("error while creating secret %s in namespace %s: %w", name, namespace, err)
 		return nil, err
 	}
 
-	logger.Debugf("Secret %s created successfully in namespace %s", name, namespace)
+	logger.Debugw("Secret created", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/secret.go:31]: Similar to previous comment.

File: internal/operator/secret.go [hunk 15]
```diff
@@ -39,6 +39,6 @@ func (o operatorClient) DeleteSecret(ctx context.Context, name string, namespace
 			Namespace: namespace,
 		},
 	}
-	logger.Debugf("Deleting secret %s from namespace %s", name, namespace)
+	logger.Debugw("Deleting secret", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/secret.go:42]: Similar to previous comment.

File: internal/operator/subscription.go [hunk 16]
```diff
@@ -25,13 +25,13 @@ func Subscriptions(catalogSource string, catalogSourceNamespace string) ([]Subsc
 
 	c, err := NewPackageServerClient()
 	if err != nil {
-		logger.Errorf("Error while creating new PackageServerClient: %s", err)
+		logger.Errorw("Error while creating new PackageServerClient", err)
```
Comment (mrhillsman) [inline internal/operator/subscription.go:28]: Errorf instead of Errorw? If Errorw need to fix format; logger.Errorw("Error while creating new PackageServerClient", "error", err)

File: internal/operator/subscription.go [hunk 17]
```diff
@@ -25,13 +25,13 @@ func Subscriptions(catalogSource string, catalogSourceNamespace string) ([]Subsc
...
 		return nil, err
 	}
 
 	packageManifests, err := c.OperatorsV1().PackageManifests("").List(context.Background(), metav1.ListOptions{})
 	if err != nil {
-		logger.Errorf("Error while listing new PackageManifest Objects : %s", err)
+		logger.Errorw("Error while listing new PackageManifest Objects", err)
```
Comment (mrhillsman) [inline internal/operator/subscription.go:34]: Errorf instead of Errorw? If Errorw need to fix format; logger.Errorw("Error while creating new PackageServerClient", "error", err)

**Review by mrhillsman — CHANGES_REQUESTED** [review]
I've left comments throughout. Some examples as well of ways to resolve; do not have to be followed exactly as provided.

File: internal/operator/operator_group.go [hunk 18]
```diff
@@ -14,7 +14,7 @@ type OperatorGroupData struct {
 }
 
 func (o *operatorClient) CreateOperatorGroup(ctx context.Context, data OperatorGroupData, namespace string) (*operatorv1.OperatorGroup, error) {
-	logger.Debugf("Creating OperatorGroup %s in namespace %s", data.Name, namespace)
+	logger.Debug("creating OperatorGroup", "operatorGroup", data.Name, "namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:17]: Debug should be Debugw
operatorGroup should be operatorgroup (currently the standard is all lowercase for key names); unless we want to change this which would require other changes.

File: internal/operator/operator_group.go [hunk 19]
```diff
@@ -26,16 +26,16 @@ func (o *operatorClient) CreateOperatorGroup(ctx context.Context, data OperatorG
 	}
 	err := o.Client.Create(ctx, operatorGroup)
 	if err != nil {
-		logger.Errorf("error while creating OperatorGroup %s: %s", data.Name, err)
+		logger.Errorf("error while creating OperatorGroup %s: %w", data.Name, err)
 		return nil, err
 	}
 
-	logger.Debugf("OperatorGroup %s is created successfully in namespace %s", data.Name, namespace)
+	logger.Debugw("OperatorGroup created", "operatorGroup", data.Name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:33]: operatorGroup should be operatorgroup
Namespace should namespace

File: internal/operator/operator_group.go [hunk 20]
```diff
@@ -26,16 +26,16 @@ func (o *operatorClient) CreateOperatorGroup(ctx context.Context, data OperatorG
...
 	return operatorGroup, nil
 }
 
 func (o *operatorClient) DeleteOperatorGroup(ctx context.Context, name string, namespace string) error {
-	logger.Debugf("Deleting OperatorGroup %s in namespace %s", name, namespace)
+	logger.Debugw("Deleting OperatorGroup", "operatorGroup", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:38]: operatorGroup should be operatorgroup
Namespace should namespace

File: internal/operator/operator_group.go [hunk 21]
```diff
@@ -44,10 +44,10 @@ func (o *operatorClient) DeleteOperatorGroup(ctx context.Context, name string, n
 	}
 	err := o.Client.Delete(ctx, &operatorGroup)
 	if err != nil {
-		logger.Errorf("error while deleting OperatorGroup: %s in namespace: %s", name, namespace, err)
+		logger.Errorf("error while deleting OperatorGroup %s in namespace %s: %w", name, namespace, err)
 		return err
 	}
 
-	logger.Debugf("OperatorGroup %s is deleted successfully from namespace %s", name, namespace)
+	logger.Debugw("OperatorGroup deleted", "operatorGroup", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/operator_group.go:51]: operatorGroup should be operatorgroup
Namespace should namespace

File: internal/operator/secret.go [hunk 22]
```diff
@@ -24,11 +24,11 @@ func (o operatorClient) CreateSecret(ctx context.Context, name string, content m
 	}
 	err := o.Client.Create(ctx, &secret, &runtimeClient.CreateOptions{})
 	if err != nil {
-		logger.Errorf("error while creating secret: %s in namespace: %s", name, namespace, err)
+		logger.Errorf("error while creating secret %s in namespace %s: %w", name, namespace, err)
 		return nil, err
 	}
 
-	logger.Debugf("Secret %s created successfully in namespace %s", name, namespace)
+	logger.Debugw("secret created", "secret", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/secret.go:31]: Namespace should namespace

File: internal/operator/secret.go [hunk 23]
```diff
@@ -39,6 +39,6 @@ func (o operatorClient) DeleteSecret(ctx context.Context, name string, namespace
 			Namespace: namespace,
 		},
 	}
-	logger.Debugf("Deleting secret %s from namespace %s", name, namespace)
+	logger.Debugw("deleting secret", "secret", name, "Namespace", namespace)
```
Comment (mrhillsman) [inline internal/operator/secret.go:42]: Namespace should namespace

**Review by mrhillsman — CHANGES_REQUESTED** [review]

**Review by mrhillsman — APPROVED** [review]
/lgtm

**Comment by skattoju** [comment]
fixed #58
