### PR TITLE
Truncate namespace when generated

### LINKED ISSUE #271: opcap 4.8 audit failing - Namespace too long
Generated namespace too long. Need to trim it down after adding 'opcap-'

### Discussed in https://github.com/opdev/opcap/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **mrhillsman** October  8, 2022</sup>
```sh
{"level":"error","ts":1665257415.5427349,"caller":"logger/logger.go:62","message":"error in audit: could not create namespace: opcap-sumologic-kubernetes-collection-helm-operator-ownnamespace: Namespace \"opcap-sumologic-kubernetes-collection-helm-operator-ownnamespace\" is invalid: [metadata.name: Invalid value: \"opcap-sumologic-kubernetes-collection-helm-operator-ownnamespace\": must be no more than 63 characters, metadata.labels: Invalid value: \"opcap-sumologic-kubernetes-collection-helm-operator-ownnamespace\": must be no more than 63 characters]","stacktrace":"github.com/opdev/opcap/internal/logger.Errorf\n\t/home/mrhillsman/Development/goland/opcap/internal/logger/logger.go:62\ngithub.com/opdev/opcap/internal/capability.(*CapAuditor).RunAudits\n\t/home/mrhillsman/Development/goland/opcap/internal/capability/auditor.go:202\ngithub.com/opdev/opcap/cmd.checkCmd.func1\n\t/home/mrhillsman/Development/goland/opcap/cmd/check.go:60\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/spf13/cobra.(*Command).ExecuteContext\n\t/home/mrhillsman/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895\ngithub.com/opdev/opcap/cmd.Execute\n\t/home/mrhillsman/Development/goland/opcap/cmd/root.go:45\nmain.main\n\t/home/mrhillsman/Development/goland/opcap/main.go:6\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```</div>

### PR DESCRIPTION
**Pull request by bcrochet**
## Description of PR

Namespaces cannot be over 63 characters. Some package names are long enough that when "opcap-" and the install mode are added, the namespace if no longer valid.

Fixes #271

Signed-off-by: Brad P. Crochet <brad@redhat.com>

## Changes (required)

* Add unit test for audit namespace
* Add fake client
* Add namespace generator function

## Checklist (required)
- [X] I have reviewed and followed the [contribution guidelines](https://github.com/opdev/opcap/blob/main/docs/contribution.md)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation if needed
- [X] I have checked that my changes pass all tests

### CODE REVIEW

**Review by yashoza19 — APPROVED** [review]
/approve

**Review by mrhillsman — CHANGES_REQUESTED** [review]
suite_test.go changes are not related namespace truncating

**Comment by bcrochet** [comment]
> suite_test.go changes are not related namespace truncating

If you look closer, you see that the test in audit_test.go uses fakeOpClient.

**Comment by bcrochet** [comment]
> > suite_test.go changes are not related namespace truncating
> 
> If you look closer, you see that the test in audit_test.go uses fakeOpClient.
> 
> https://github.com/opdev/opcap/pull/272/files#diff-ab1655423e7300f688424dbbb24d3bd3a5b054bb367b88f9b300dbda04078267R22

Actually, I'll change it to what I did in #275. It's a cleaner impl.

**Comment by mrhillsman** [comment]
@bcrochet I guess the only concern than is if this PR for some strange reason needs to be touched do the changes to suite_test still need to be around?

File: internal/capability/audit.go [hunk 1]
```diff
@@ -52,8 +52,18 @@ type capAudit struct {
 	operands []unstructured.Unstructured
 }
 
+func generateNamespace(packageName string, installMode string) string {
+	installModeString := string(installMode)
+	namespaceLength := 63 - len("opcap-") - len(installModeString) - 1
```
Comment (skattoju) [inline internal/capability/audit.go:57]: neat!

**Review by skattoju — APPROVED** [review]

**Review by mrhillsman — APPROVED** [review]
